CREATE TABLE 1p_b2b_nto.OTB_PURCHASE_ORDER_MASTER (  
  TRACKING_NUMBER INT NOT NULL AUTO_INCREMENT,
  PURCHASE_ORDER_NUMBER VARCHAR(30) NOT NULL,
  NTO_LOB VARCHAR(100) NOT NULL,
  SUPPLIER VARCHAR(100) NOT NULL,
  PO_ACK_STATUS VARCHAR(15) NOT NULL,
  TRANSMISSION_MODE VARCHAR(10) NOT NULL,
  PO_CREATE_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PO_ACK_DTTM TIMESTAMP,
  PO_BUSINESS_MSG text NOT NULL,
  PO_ACK_BUSINESS_MSG text,
  PRIMARY KEY (TRACKING_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;